In [1]:
import numpy as np

## Boolean Indexing


In [2]:
# Book Page Number.98

In [3]:
# I’m going to use here the randn function in numpy.random to generate
#some random normally distributed data:


In [4]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
 data = np.random.randn(7, 4)


In [7]:
data

array([[ 0.04167293, -0.05411289,  0.23550825, -0.56675289],
       [ 1.09561007,  0.79163501, -0.37996934,  0.36371252],
       [-1.01305975, -0.13900872, -0.77701777, -0.54573957],
       [-1.39663973,  0.1685694 , -0.65910197,  1.33550466],
       [-2.82895801,  0.5715336 ,  1.87439906, -0.43010573],
       [-0.13497049,  1.589948  ,  0.09571216, -0.45518458],
       [-0.70446271, -0.98621667, -0.20129333,  0.74648276]])

In [10]:
data1 = np.random.randn(4,7)

In [11]:
data1

array([[ 0.16332679,  0.72557785,  1.65548514,  0.05664156, -0.97618471,
         2.07827354, -0.62675355],
       [-0.21127923,  1.20139001, -1.13422986, -0.24035538,  0.66153112,
         0.25645254, -0.56088456],
       [-1.74556735,  1.59342466, -0.38779327,  1.36483525,  0.68785534,
        -1.31351618,  1.82292512],
       [-0.36756461,  0.29601789,  0.66012398,  0.65371097,  1.35981218,
        -0.22779769,  0.45868534]])

In [12]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [13]:
data

array([[ 0.04167293, -0.05411289,  0.23550825, -0.56675289],
       [ 1.09561007,  0.79163501, -0.37996934,  0.36371252],
       [-1.01305975, -0.13900872, -0.77701777, -0.54573957],
       [-1.39663973,  0.1685694 , -0.65910197,  1.33550466],
       [-2.82895801,  0.5715336 ,  1.87439906, -0.43010573],
       [-0.13497049,  1.589948  ,  0.09571216, -0.45518458],
       [-0.70446271, -0.98621667, -0.20129333,  0.74648276]])

In [14]:
 names == 'Bob'


array([ True, False, False,  True, False, False, False])

In [18]:
"""  This boolean array can be passed when indexing the array:
     Suppose each name corresponds to a row in the data array and we wanted to select
     all the rows with corresponding name 'Bob'
"""

"  This boolean array can be passed when indexing the array:\n     Suppose each name corresponds to a row in the data array and we wanted to select\n     all the rows with corresponding name 'Bob'\n"

In [16]:
 data[names == 'Bob']


array([[ 0.04167293, -0.05411289,  0.23550825, -0.56675289],
       [-1.39663973,  0.1685694 , -0.65910197,  1.33550466]])

In [20]:
 data[names == 'Bob', 2:]  #  we find in data array , "bob" rows and 2nd to last columns values.


array([[ 0.23550825, -0.56675289],
       [-0.65910197,  1.33550466]])

In [21]:
 data[names == 'Bob', 3]  #  we find in data array , "bob" rows and 3nd columns values.


array([-0.56675289,  1.33550466])

In [25]:
#  To select everything but 'Bob', you can either use != or negate the condition using ~: 


In [26]:
 names != 'Bob'


array([False,  True,  True, False,  True,  True,  True])

In [27]:
 data[~(names == 'Bob')]


array([[ 1.09561007,  0.79163501, -0.37996934,  0.36371252],
       [-1.01305975, -0.13900872, -0.77701777, -0.54573957],
       [-2.82895801,  0.5715336 ,  1.87439906, -0.43010573],
       [-0.13497049,  1.589948  ,  0.09571216, -0.45518458],
       [-0.70446271, -0.98621667, -0.20129333,  0.74648276]])

In [29]:
# The ~ operator can be useful when you want to invert a general condition:


In [30]:
 cond = names == 'Bob'


In [31]:
 data[~cond]


array([[ 1.09561007,  0.79163501, -0.37996934,  0.36371252],
       [-1.01305975, -0.13900872, -0.77701777, -0.54573957],
       [-2.82895801,  0.5715336 ,  1.87439906, -0.43010573],
       [-0.13497049,  1.589948  ,  0.09571216, -0.45518458],
       [-0.70446271, -0.98621667, -0.20129333,  0.74648276]])

In [32]:
 #   data[~(names == 'Bob')]
#   data[~cond]                       Both conditions doing same work


In [33]:
# boolean arithmetic operators like & (and) and | (or):

In [34]:
 mask = (names == 'Bob') | (names == 'Will')


In [35]:
mask

array([ True, False,  True,  True,  True, False, False])

In [36]:
 data[mask]


array([[ 0.04167293, -0.05411289,  0.23550825, -0.56675289],
       [-1.01305975, -0.13900872, -0.77701777, -0.54573957],
       [-1.39663973,  0.1685694 , -0.65910197,  1.33550466],
       [-2.82895801,  0.5715336 ,  1.87439906, -0.43010573]])

In [50]:
#  Setting values with boolean arrays works in a common-sense way. To set all of the
#  negative values in data to 0 we need only do:

In [55]:
 data[data < 0] = 0


In [56]:
data

array([[0.04167293, 9.        , 0.23550825, 9.        ],
       [1.09561007, 0.79163501, 9.        , 0.36371252],
       [9.        , 9.        , 9.        , 9.        ],
       [9.        , 0.1685694 , 9.        , 1.33550466],
       [9.        , 0.5715336 , 1.87439906, 9.        ],
       [9.        , 1.589948  , 0.09571216, 9.        ],
       [9.        , 9.        , 9.        , 0.74648276]])

In [57]:
# Setting whole rows or columns using a one-dimensional boolean array is also easy:


In [58]:
 data[names != 'Joe'] = 7


In [67]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.09561007, 0.79163501, 9.        , 0.36371252],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [9.        , 1.589948  , 0.09571216, 9.        ],
       [9.        , 9.        , 9.        , 0.74648276]])

# Fancy Indexing


In [68]:
# Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.
#Suppose we had an 8 × 4 array: 


In [69]:
 arr = np.empty((8, 4))


In [72]:
 for i in range(8):
       arr[i] = i

In [73]:
 arr = np.empty((8, 4))
 print(arr)


[[4.63636107e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [74]:
 for i in range(8):
       arr[i] = i

In [75]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [76]:
 arr[[4, 3, 0, 6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [77]:
 arr[[-3, -5, -7]]


array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [78]:
 arr = np.arange(32).reshape((8, 4))


In [79]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [80]:
In [125]: arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [81]:
#  which is the rectangular region formed by
# selecting a subset of the matrix’s rows and columns. Here is one way to get that: