In [1]:
import numpy as np

# Shape of an Array


In [2]:
# Print the shape of a 2-D array:



In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

print(arr.ndim)

# The example above returns (2, 4), which means that the array has 2 dimensions, 
# and each dimension has 4 elements.



(2, 4)
2


In [7]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that
#  last dimension has value 4:



In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping


In [10]:
# Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension.

# By reshaping we can add or remove dimensions or change number of elements in each dimension.

Reshape From 1-D to 2-D


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.ndim)

1


In [13]:
arr2 = arr.reshape(4,3)

In [20]:
print(arr2.ndim)
print(arr2)

2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
ar = arr.reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Reshape From 1-D to 3-D


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [24]:
array3 = arr.reshape(2,3,2)

In [25]:
print(array3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
ar = arr.reshape(3,2,2)
print(ar)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4))

print(arr.reshape(2,4).base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


Unknown Dimension


In [30]:
# Pass -1 as the value, and NumPy will calculate this number for you.



In [33]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
ar = np.array([1,2,3,3,4,5,6,7,8,9,0,9,8,5])

ar2 = ar.reshape(2,7,-1)
ar2

array([[[1],
        [2],
        [3],
        [3],
        [4],
        [5],
        [6]],

       [[7],
        [8],
        [9],
        [0],
        [9],
        [8],
        [5]]])

# Flattening the arrays


In [39]:
# Flattening array means converting a multidimensional array into a 1D array.

# We can use reshape(-1) to do this.

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [42]:
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [50]:
arr = np.arange(1,33)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [52]:
ar = arr.reshape(2,4,4)

In [53]:
print(ar.ndim)

3


In [54]:
print(ar)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


In [55]:
a = ar.reshape(4,2,4)

In [59]:
print(a)

print(a.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]


 [[[25 26]
   [27 28]]

  [[29 30]
   [31 32]]]]
4


In [57]:
a = ar.reshape(4,2,2,2)

In [60]:
a.ndim

4

In [61]:
a

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]],


       [[[25, 26],
         [27, 28]],

        [[29, 30],
         [31, 32]]]])

# NumPy Array Iterating


In [62]:

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [63]:
# Iterating 2-D Arrays


In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [67]:
#  Iterating Arrays Using nditer()


arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
