# NumPy Data Types


In [1]:
# By default Python have these data types:
"""
strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

"""

In [2]:
# Below is a list of all data types in NumPy and the characters used to represent them.
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# The NumPy array object has a property called dtype that returns the data type of the array:

In [5]:
arr = np.array([1,2,3,4,5,6])

In [6]:
array = np.array([10, 20, 30, 40, 50])

print(array)

[10 20 30 40 50]


In [7]:
array

array([10, 20, 30, 40, 50])

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
print(arr.dtype)

int32


In [10]:
arr1 = np.array(['apple', 'banana', 'cherry'])


In [11]:
print(arr1.dtype)

<U6


# Creating Arrays With a Defined Data Type


In [12]:
# We use the array() function to create arrays, this function can take an optional argument:
# dtype that allows us to define the expected data type of the array elements:



In [12]:
arr = np.array([1, 2, 3, 4], dtype='S')


In [13]:
print(arr)

[b'1' b'2' b'3' b'4']


In [14]:
arr.dtype

dtype('S1')

In [16]:
# Create an array with data type 4 bytes integer:

In [15]:
arr = np.array([1, 2, 3, 4,5,], dtype='i4')


In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr1 = np.array([1,2,3,4,5,6,7], dtype = 'i8')

In [19]:
arr1.dtype

dtype('int64')

# Converting Data Type on Existing Arrays


In [20]:
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.



In [21]:
arr = np.array([1.1, 2.1, 3.1])


In [22]:
arr.dtype

dtype('float64')

In [23]:
newarr = arr.astype('i8')   #  int64

newarr1 = arr.astype('i4')  #  int32

In [24]:

print(newarr1.dtype)

newarr.dtype

int32


dtype('int64')

In [25]:
ar = np.array([1.1,2.2,.3,4.1,])

In [26]:
ar.dtype

dtype('float64')

In [27]:
newarr = ar.astype('f')

In [28]:
newarr.dtype

dtype('float32')

In [29]:
inte = ar.astype('i4')

In [30]:
inte.dtype

dtype('int32')

In [31]:
arr = np.array([1.1, 2.1, 3.1])

newar = arr.astype(int)

print(newar.dtype)
newar


int32


array([1, 2, 3])

In [32]:
# Change data type from integer to boolean:



In [47]:
arr = np.array([1, 0, -3 , 0, 9.0, 0.7])


In [48]:
new = arr.astype(bool)
print(new.dtype)
print(new)

bool
[ True False  True False  True  True]


# NumPy Array Copy vs View


COPY:


 The copy owns the data and any changes made to the copy will not affect original array, 
 and any changes made to the original array will not affect the copy.



In [49]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

arr[0] = 42

In [50]:
print(x)

[1 2 3 4 5]


In [51]:
arr

array([42,  2,  3,  4,  5])

VIEW:


The view does not own the data and any changes made to the view will affect the original array,
and any changes made to the original array will affect the view.



In [52]:

arr = np.array([1, 2, 3, 4, 5])
x1 = arr.view()

arr[0] = 42

In [55]:
x1

array([42,  2,  3,  4,  5])

In [56]:
arr

array([42,  2,  3,  4,  5])

Check if Array Owns it's Data


In [59]:
arr = np.array([1, 2.2, 3, 4, 5.1, "hello", '%'])
arr.dtype

dtype('<U32')

In [60]:
li = [1, 2.2, 3, 4, 5.1, "hello", '%']


In [62]:
print(li)

[1, 2.2, 3, 4, 5.1, 'hello', '%']


In [63]:
type(li)

list

In [74]:
arr = np.array([1, 2.2, 3, 4, 5.1,10])

x = arr.copy()

y = arr.view()

In [75]:
print(x.base)
x

None


array([ 1. ,  2.2,  3. ,  4. ,  5.1, 10. ])

In [77]:
print(y.base)

[ 1.   2.2  3.   4.   5.1 10. ]
