# Pandas Series

In [ ]:
# must need to import pandas
# Creating Series in pandas

import pandas as pd
obj = pd.Series([4, 7, -5, 3])    
print(obj)

In [26]:
import pandas as rana

data = rana.Series([1,2,3,4,45,50])
data

0     1
1     2
2     3
3     4
4    45
5    50
dtype: int64

In [27]:
import pandas
data = pandas.Series([1,2,3,4,45,50])
data

0     1
1     2
2     3
3     4
4    45
5    50
dtype: int64

# pandas Series has two things in one object
1 Values
-  

2 Index
-

In [9]:
sales = pd.Series([100, 200, 100, 400])

print(sales.values)
print(sales.index)
print(sales)

[100 200 100 400]
RangeIndex(start=0, stop=4, step=1)
0    100
1    200
2    100
3    400
dtype: int64


In [30]:
sales = pd.Series([100, 200, 400, 700], index = ['Jan', 'Feb', 'Mar','Apr'])
print(sales)
print(sales.values)
print(sales.index)

Jan    100
Feb    200
Mar    400
Apr    700
dtype: int64
[100 200 400 700]
Index(['Jan', 'Feb', 'Mar', 'Apr'], dtype='object')


# create a pandas series to store a canteen data to hold values of how many sandwitches are sold each days (one week)

In [31]:
sw = pd.Series([20, 30, 20, 25, 30, 40, 0], 
               index = ['mon', 'tue', 'wed', 'thr','fri', 'sat', 'sun'])
print(sw)

mon    20
tue    30
wed    20
thr    25
fri    30
sat    40
sun     0
dtype: int64


In [17]:
"""sw = pd.Series(["jan", "feb", 20, 25, 30, "jun", 0.01], 
               
               index = ['mon', 'tue', 20, 'thr','fri', 90.10, 'sun'])
print(sw)
"""

'sw = pd.Series(["jan", "feb", 20, 25, 30, "jun", 0.01], \n               \n               index = [\'mon\', \'tue\', 20, \'thr\',\'fri\', 90.10, \'sun\'])\nprint(sw)\n'

In [19]:
print(sw[1])

print(sw["tue"])


30
30


In [20]:
print(sw[  [3,5] ])

print(sw[ [ "tue", "thr"] ])

thr    25
sat    40
dtype: int64
tue    30
thr    25
dtype: int64


# for providing multipe index for selecting element in an pd series, use array notation

In [35]:
print(sw < 20)
print()
print(sw[sw > 20])
print()
print(sw[sw<20])

mon    False
tue    False
wed    False
thr    False
fri    False
sat    False
sun     True
dtype: bool

tue    30
thr    25
fri    30
sat    40
dtype: int64

sun    0
dtype: int64


In [22]:
#sw * 2
sw = sw * 2
print(sw)

mon    40
tue    60
wed    40
thr    50
fri    60
sat    80
sun     0
dtype: int64


In [23]:
sw = sw /2
print(sw)

mon    20.0
tue    30.0
wed    20.0
thr    25.0
fri    30.0
sat    40.0
sun     0.0
dtype: float64


In [24]:
sw = sw //2
print(sw)

mon    10.0
tue    15.0
wed    10.0
thr    12.0
fri    15.0
sat    20.0
sun     0.0
dtype: float64


In [25]:
'mon' in sw

True

# taking input from numpy arrays and converting to Pandas Series

In [39]:
import numpy as np

ar = np.array([3,2,4,5,6])   # creating array 
ind = np.array( ['a', 'b', 'c', 'd', 'e']) 

obj2 = pd.Series(ar, index = ind)    
print(obj2)

a    3
b    2
c    4
d    5
e    6
dtype: int32


In [37]:
ar

array([3, 2, 4, 5, 6])

In [38]:
ind

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

# creating dictionary and then converting to pandas series

In [41]:
sdata = {"Sindh": 35000, "Panjab": 45000, "KPK": 30000, "Balochistan": 20000} 
# creating dictionary
tax_by_state = pd.Series(sdata)  # Converting to series
print(tax_by_state)
print()
print(tax_by_state.index)

Sindh          35000
Panjab         45000
KPK            30000
Balochistan    20000
dtype: int64

Index(['Sindh', 'Panjab', 'KPK', 'Balochistan'], dtype='object')


# if index more than values :

In [45]:
sdata = {"Sindh": 35000, "Panjab": 45000, "KPK": 30000, "Balochistan": 20000}
tax_by_state = pd.Series(sdata, index = ["Panjab", "Sindh", "KPK", "Balochistan", "GB"])

#print(tax_by_state)

print(pd.isnull(tax_by_state))    # isnull() function checking null values

Panjab         False
Sindh          False
KPK            False
Balochistan    False
GB              True
dtype: bool


In [47]:
print(tax_by_state[-1])
print()
print(tax_by_state['GB'])

nan

nan


In [46]:
# NaN values mean, values does not exist in pandas series

pd.isnull(tax_by_state)
tax_by_state.isnull()

Panjab         False
Sindh          False
KPK            False
Balochistan    False
GB              True
dtype: bool

In [50]:
sw = pd.Series([20, 30, 20, 25, 30, 40, 0], 
               index = ['mon', 'tue', 'wed', 'thr','fri', 'sat', 'sun'])

print(sw)
sw.index = ["m", "t", "w", "t", "f", "s", "s"]   # changing index
print(sw)

mon    20
tue    30
wed    20
thr    25
fri    30
sat    40
sun     0
dtype: int64
m    20
t    30
w    20
t    25
f    30
s    40
s     0
dtype: int64
